/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/podcast/{podcast_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                podcast_id: string;
            };
            cookie?: never;
        };
        /** Get all comments for a podcast */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    podcast_id: string;
                    /** @description Podcast ID */
                    podcastId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            commentId?: string;
                            created_by?: string;
                            comment?: string;
                            /** Format: date-time */
                            created_at?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Post a comment to a podcast */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    podcast_id: string;
                    /** @description Podcast ID */
                    podcastId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Comment content */
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description Comment created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            commentId?: string;
                            success?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comment/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a comment */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    comment_id: string;
                    /** @description Comment ID */
                    commentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Comment deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
